pool: Default

trigger:
- release

variables:
  dockerImageName: 'sadik8143/springclinic'  
  dockerImageTag: '46' 
                       

stages:
  - stage: continuous_deployment
    jobs:
      - job: 'deployment'
        displayName: 'Deploy into cluster'
        steps:
          
          - task: CmdLine@2
            displayName: 'Debug Docker Pull Command'
            inputs:
              script: |
                echo "Pulling image $(dockerImageName):$(dockerImageTag)"
                docker pull $(dockerImageName):$(dockerImageTag)


          
          - task: CmdLine@2
            displayName: 'Scanning image'
            inputs:
              script: |
                trivy image $(dockerImageName):$(dockerImageTag) -o trivy-report.xml

          
          - task: PublishPipelineArtifact@1
            displayName: 'Publish Trivy Report'
            inputs:
              targetPath: 'trivy-report.xml'
              artifact: 'TrivyReport'

          - task: Bash@3
            inputs:
              targetType: 'inline'
              script: |
                terraform init 
                terraform apply -var-file="default.tfvars" -auto-approve
              workingDirectory: './infra'


          - task: Bash@3
            inputs:
              targetType: 'inline'
              script: |
                kubectl apply -f spc-deployement.yml
                kubectl get svc
              

          














        








