
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-deploy
spec:
  minReadySeconds: 5
  replicas: 4
  selector:
    matchLabels: 
      app: spring
  strategy: 
    type: RollingUpdate
    rollingUpdate: 
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels: 
        app: spring

    spec:
      containers: 
        - image: sadik8143/springclinic:46
          name: webcont
          resources: 
            limits:
              cpu: 500m
              memory: 256M
            requests:
              cpu: 100m
              memory: 64M
          ports:
            - containerPort: 8080

          livenessProbe: 
            failureThreshold: 3
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 10
          readinessProbe: 
            failureThreshold: 3
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 10         

---
apiVersion: v1
kind: Service
metadata:
  name: spring-svc
spec:
  selector:  
    app: spring

  type: NodePort
  ports: 
    - port: 8080
      targetPort: 8080

