---
    name: continous deployement
    on:
        push:
            branches:
                - release
    jobs:
      deployment_cluster:
         runs-on: ubuntu-latest
         steps: 
          - name: Checkout code
            uses: actions/checkout@v4
    
    
          - name: Log in to Docker Hub
            uses: docker/login-action@v2
            with:
              username: sadik8143
              password: Sadik@8143
          - name: pulling the image
            run: |
              docker pull sadik8143/springpetclinic:1.0
          - name: installing trivy
            run: |
                sudo apt-get install wget apt-transport-https gnupg lsb-release
                wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | gpg --dearmor | sudo tee /usr/share/keyrings/trivy.gpg > /dev/null
                echo "deb [signed-by=/usr/share/keyrings/trivy.gpg] https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main" | sudo tee -a /etc/apt/sources.list.d/trivy.list
                sudo apt-get update
                sudo apt-get install trivy -y
      
          - name: Scan the image and save results
            run: |
                  trivy image --format json --output trivy-results.json sadik8143/springpetclinic:1.0
      
          - name: Upload Trivy scan results
            uses: actions/upload-artifact@v3
            with:
                name: trivy-results
                path: trivy-results.json 
          - name: Azure login
            uses: azure/login@v2
            with:
                  client-id: 74cb6831-0dbb-4be1-8206-fd4df301cdc2
                  tenant-id:  15647947-d1c2-4096-87a2-acbd9b0c51a4
                  subscription-id: 088435c4-2a9a-470a-ba21-96097929afcb
            
    