---
    name: continous deployement
    on:
        push:
            branches:
                - release
    jobs:
      deployment_cluster:
         runs-on: ubuntu-latest
         permissions:
          id-token: write 
          contents: read 

         steps: 
          - name: Log in to Docker Hub
            uses: docker/login-action@v2
            with:
             username: ${{ secrets.USER_NAME }}
             password: ${{ secrets.PASSWORD }}

          - name: Pull Docker Image
            uses: docker/build-push-action@v6
            with:
               push: false
               tags: sadik8143/spc:1.0
               load: true

          - name: Run Trivy Scan
            id: trivy_scan
            uses: aquasecurity/trivy-action@master
            with:
                    image-ref: 'sadik8143/spc:1.0'
                    format: 'json'
                    output: trivy-results.json
                    exit-code: '1'
                    ignore-unfixed: false
                    severity: 'HIGH,CRITICAL'
                    continue-on-error: true
          
          - name: Upload Trivy Scan Results
            if: steps.trivy_scan.outcome == 'success'
            uses: actions/upload-artifact@v4
            with:
                    name: trivy-scan-results
                    path: trivy-results.json

          - name: Azure login
            uses: azure/login@v2
            with:
              creds: '{
                              "clientId": "22008831-1561-42ff-879f-e7a0ca7298ef",
                              "clientSecret": "xk~8Q~_LmrmyDOphBwMcSEJhSTgaP4cCTc~jrb5q",
                              "subscriptionId": "48779e5a-57d5-432c-8ddf-d51b82b18f09",
                              "tenantId": "99ef06df-664d-4769-9eaa-9f4ba6706a0d",
                              "activeDirectoryEndpointUrl": "https://login.microsoftonline.com",
                              "resourceManagerEndpointUrl": "https://management.azure.com/",
                              "activeDirectoryGraphResourceId": "https://graph.windows.net/",
                              "sqlManagementEndpointUrl": "https://management.core.windows.net:8443/",
                              "galleryEndpointUrl": "https://gallery.azure.com/",
                              "managementEndpointUrl": "https://management.core.windows.net/"}'
        
          - name: Azure CLI script
            uses: azure/cli@v2
            with:
                azcliversion: latest
                inlineScript: |
                  az account show
            
               

         


