---
    name: continous deployement
    on:
        push:
            branches:
                - release
    jobs:
      deployment_cluster:
         runs-on: ubuntu-latest
         permissions:
          id-token: write 
          contents: read 

         steps: 
          - name: Log in to Docker Hub
            uses: docker/login-action@v2
            with:
             username: ${{ secrets.USER_NAME }}
             password: ${{ secrets.PASSWORD }}

          - name: Pull Docker Image
            uses: docker/build-push-action@v6
            with:
               push: false
               tags: sadik8143/spc:1.0
               load: true