name: Continous integration
on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - main
jobs:
  build_docker_image:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: sadik8143
          password: Sadik@8143
  
